### ISSUE TITLE
Структура БД

### ISSUE THREAD

**Issue by biakaveron** [kohanaworld/kohana.world#10]
Частично пересекается с задачей "импорт с github", но наверное стоит выделить в свой тикет. Надо бы потихоньку набрасывать черновой вариант БД, пока можно просто на уровне общих сущностей и принципиальных полей/связей. Так как изменения на данной стадии будут практически постоянными, можно не выдумывать и начать это дело в Google Docs, тупо в таблице. Когда со структурой определимся, можно будет и в Workbench'е красивости рисовать :)

**Comment by smgladkovskiy** [comment]
true.

Сделал документ и набросал примерный шаблон заполнения. Шаблон пусть будет отдельным листом. Другие листы пользовать под группы таблиц общего назначения...

https://spreadsheets.google.com/ccc?key=0Aro_Snud_pvjdFVBaDBSTU5DZkgwSlJlODI2aURfOHc&hl=ru&authkey=CLnUz9YF

сейчас продублирую в теме на форуме.

**Comment by biakaveron** [comment]
Накидал самый минимум (модули + разработчики), в который можно кидать данные от Github API. Пока непонятно, как быть с отдельными релизами (тэгами), тем более проблемы с зависимостями и совместимостью как правило определяются именно для них, а не для модулей

**Comment by smgladkovskiy** [comment]
Сделали репозиторий [kw-bd_scheme](https://github.com/kohana-world/kw-db_scheme/), где будет выкладываться схема БД в формате [MySQL Workbench](http://wb.mysql.com/). Любые изменения в схеме подкрепляйте подробным описанием в задаче (а лучше наоборот - сначала задачу в репозитории, а затем после утверждения коммит)...
