### ISSUE TITLE
Способ хранения меток времени

### ISSUE THREAD

**Issue by biakaveron** [kohanaworld/kohana.world#11]
Холиварный вопрос - как будем время хранить? :) 
- В виде integer
- В формате timestamp

Есть преимущества (и недостатки) как у одного, так и у другого подхода.

**Comment by paulchubatyy** [comment]
Я бы использовал timestamp, так как можно использовать с полем такого вида функции по работе с датой. Хотя сначала мы скорее всего не будем использовать этих функций.

**Comment by ukko** [comment]
timestamp без триггеров

**Comment by biakaveron** [comment]
Собственно почему спрашиваю вашего мнения - вот [интересное обсуждение](http://forum.kohanaframework.org/discussion/comment/49934/). Преимущество полей TimeStamp/DataTime в возможности использовать СУБДшные функции. Я не являюсь сильным специалистом в разных СУБД, кто-то может мне сказать - функции типа DATEDIFF имеют один и те же названия в MySQL, SQLite, PostgreSQL и т.д.? Сомневаюсь :)

А на стороне PHP, как правильно указано по той ссылке, все равно время конвертируется в число.

**Comment by slider23** [comment]
Я у себя юзаю datetime только если знаю, что потом придется лазить в БД и что-то там руками ковырять. У нас не тот случай, поэтому, думаю, int.

**Comment by paulchubatyy** [comment]
@medar timestamp хранится как int,  при выборке результат будет в формате datetime

**Comment by biakaveron** [comment]
который все равно придется приводить к другому формату ))

**Comment by smgladkovskiy** [comment]
Я всегда использую то, что нужно для задачи. Если нужно хранить дату рождения пользователя, её логичней держать в DATE. Если ведётся лог событий, то тут уж без timestamp не обойтись. Каждое значение должно быть по назначению... :)

Опять-таки, если мы завязываемся на изменения в гитхабе, то там время возвращается в DATETIME. Отсюда, целесообразнее и нам трейсить событие вплоть до секунд. А это - timestamp (DATETIME тоже можно использовать, но ввиду того, что приняли ORM как ОРМ-библиотеку, лучше использовать более понятные для неё формат). По остальным задачам будет видно, что лучше применять...

**Comment by smgladkovskiy** [comment]
Так как предложений больше не поступало и ввиду того, что GitHub выдаёт всю информацию о времени в виде datetime, то мы будем хранить временные метки в формате unix timestamp (int(11)).
