### ISSUE TITLE
Заглушка для заглавной страницы kohana-modules.com

### ISSUE THREAD

**Issue by biakaveron** [kohanaworld/kohana.world#12]
Пока мы не выкатываем ничего красивого, надо бы что-то повесить на основной сайт. Вижу два варианта:
- Просто html, например с информацией о сайте (зачем, кто и т.д.)
- Вешаем форму для сбора email'ов, чтобы написать, когда мы "откроемся". В этом случае понадобится написание кода. Я вроде раньше видел модуль (под 2.3.4 вроде), но навскидку не нашел - может кто знает? Если что, написать в принципе недолго.

**Comment by smgladkovskiy** [comment]
может, что-то простое?
http://tutorialzine.com/2010/10/ajaxed-coming-soon-page/

**Comment by biakaveron** [comment]
Ну да, типа такого - страничка с формой ;) Тупо кидаем в БД email, потом сообщим

**Comment by NARKOZ** [comment]
Подтверждение почты нужно?

**Comment by biakaveron** [comment]
А зачем? Мы ж тупо кинем письмо, а не организовываем подписку на журнал.

**Comment by zares** [comment]
Перемещено в
https://github.com/russiankohana/kohanaworld/issues/#issue/16

**Comment by smgladkovskiy** [comment]
сделано
