### ISSUE TITLE
Размещение вакансий и резюме

### ISSUE THREAD

**Issue by biakaveron** [kohanaworld/kohana.world#15]
В общем, нечего kohanajobs все сливки снимать, будем конкурировать :) Тикет на будущее, по приоритету явно ниже, чем запустить работу с модулями. Чтобы не забыть

**Comment by xbagir** [comment]
Делал проект www.vdelah.ru. Очень подходит под эту тематику, и сделан он для всех фреймворков. Допилить, подшаманить - и как раз есть все необходимое. 
Предлагаю его взять, под этот проект.

**Comment by biakaveron** [comment]
Когда начнем реализовывать идею, создадим соответствующий модуль KW и в нем будем обсуждать. Закрываю
