### ISSUE TITLE
Графика сайта

### ISSUE THREAD

**Issue by zares** [kohanaworld/kohana.world#16]
Логототип + другие элементы дизайна...
думаю, что удобнее все это будет в 
одной теме.

Идея с боксами выглядит неплохо.
Мое предложение лежит здесь: 
http://zalil.ru/30463163

Если оно заслуживает внимания - можно вывесить для 
дальнейшего публичного обсуждения и корректировок...

**Comment by paulchubatyy** [comment]
Порадовала пятая картинка. +1 за нее.

**Comment by zares** [comment]
Спасибо, Xobb.
Что-то здесь очень штильно.
Право, я себя чувствую не в своей тарелке...

**Comment by smgladkovskiy** [comment]
@zares Попробуй jabber-конфу... там проще обсудить и предложения выдвинуть...

**Comment by biakaveron** [comment]
Для обсуждения дизайна есть #1 и #30 (новая версия), для лого - #14. Закрываю.
