### ISSUE TITLE
Соглашение об именовании полей БД в Jelly модели

### ISSUE THREAD

**Issue by smgladkovskiy** [kohanaworld/kohana.world#17]
Если коротко, то нужно прийти к соглашению, как записывать поля БД в описании Jelly модели. Есть два способа: вызов класса и использование фабрики:
1. вариант с вызовом класса:
       'some_field' => new Jelly_Field_String(array(
           ...
       )),
2. вариант с использованием фабрики:
       'some_field' => Jelly::field('String', array(
           ...
        )),

Предлагаю обсудить все за и против.

Вариант первый полезен тем, что что будут выдавать подсказки IDE.
Второй вариант, как мне кажется, более kohana-style и элегантнее... :)

**Comment by biakaveron** [comment]
Да, раз мы используем Jelly::factory() и прочее, наверное стоит использовать Jelly::field(). Тем более, что подсказка кроме как при выборе типа поля больше ничем там не поможет...

**Comment by smgladkovskiy** [comment]
больше предложений не поступало? Закрываем "обсуждение", сойдясь на фабрике?

**Comment by biakaveron** [comment]
принято
