### ISSUE TITLE
Переименование сообщества

### ISSUE THREAD

**Issue by smgladkovskiy** [kohanaworld/kohana.world#18]
В целях охватить не только русскоязычное комьюнити kohana-разработчиков, предлагается  переименовать сообщество. Настоящее имя **russiankohana** слишком говорящее.

Вариант для переименования: **kohana-world**

**Comment by NARKOZ** [comment]
Вариант: kohana-brothers

**Comment by biakaveron** [comment]
Помимо охватывания сообщества помним о текущей задаче - создании портала kohana-world.com. В связи с этим первый вариант выглядит самым логичным на данный момент. По крайней мере пока мы не создали юрлицо ))

**Comment by ukko** [comment]
я за kohana-world

**Comment by biakaveron** [comment]
Сообщество переименовано в kohana-world.com (по доменному имени), обсуждение закрываю.
