### ISSUE TITLE
Импорт данных с github

### ISSUE THREAD

**Issue by ukko** [kohanaworld/kohana.world#2]
Разобраться с модулями импорта информации c github.

Создать модели и проработать сущности:
- Проработать сущность "модуль коханы" (зависимость, версии)
- Сущность "репозитарий"
- Сущность "автор"

**Comment by biakaveron** [comment]
Я так полагаю, модуль - это один из релизов репозитория? Или как?

Еще есть тэги, ветки и коммиты (хотя они наверное не понадобятся)

**Comment by smgladkovskiy** [comment]
ммм... задача закрыта или просто тыкнуто "close and comment"? :)

**Comment by biakaveron** [comment]
Ага, я на нее тыцкнул )) Правда вроде обратно вернул уже

**Comment by ukko** [comment]
нет, не вернул.. надо поаккуратнее с этими кнопочками

**Comment by biakaveron** [comment]
Ща пойду искать/делать скрипт для greasemonkey, скрывающий эту кнопень... ))

**Comment by paulchubatyy** [comment]
Я думаю, что сущность модуля должна совпадать с сущностью репозитория. А ветки и тэги — это уже лейблы модуля, которые мы можем привязать к релизам kohana. Тоесть ветка 3.0/master и 3.0/develop модуля (или репозитория) kohana/database совместима с kohana 3.0, а ветки 3.1/master и 3.1/develop — соответственно с kohana 3.1.

Коммиты в первой итерации вообще думаю лучше не трогать, к ним вернемся позже.

**Comment by ukko** [comment]
Можно так же на странице модуля сделать ссылку на скачку zip архива с модулем. 

Про коммиты - тут спорный вопрос,главное тут как говорит Xobb - указывать для нужной ветки или тега - версию коханы, для сохранения совместимости.

**Comment by ukko** [comment]
В эту же сущность "модуля" нужно добавить понятие ссылки на документацию. 

Т.е. просто блок ссылок на запись в блогах о использовании этого модуля.

**Comment by biakaveron** [comment]
Полагаю, что помимо собственно "модуля" надо будет предусмотреть сущность "релиз" (основываясь на тэгах репозитория). Не знаю насчет веток, часто они содержат нерабочий/промежуточный код, и предлагать их скачать не стоит. Кроме того, разные релизы могут иметь свои зависимости и совместимость. Свою документацию, в конце концов...

**Comment by biakaveron** [comment]
Зависимости кстати можно парсить автоматически из файла .gitmodules релиза. Правда, там придется немного подшаманить с поиском оригинального модуля (автор ведь может вместо kohana/core указать shadowhand/core или что-то подобное). Отсюда мысль о хранении списка форков для модулей, чтобы их использовать как псевдонимы - можно будет быстро добраться до оригинала.

**Comment by smgladkovskiy** [comment]
Общая задача выполнена: информация по модулям и разработчикам вытягивается с github. Дальнейшую работу необходимо конкретизировать и разбить по более конкретным задачам.
