### ISSUE TITLE
Оптимизация работы краулера

### ISSUE THREAD

**Issue by biakaveron** [kohanaworld/kohana.world#20]
Первый день работы краулера выявил аномальную активность работы с БД в период его работы. Поставлена задача - минимизировать количество запросов.

Приложение: [График нагрузки](https://docs.google.com/leaf?id=0B7o_Snud_pvjN2RiOGVlODMtZTU5NC00YzFlLWE1ZWEtYjc5MGNkY2QyZDQw&hl=ru)

**Comment by NARKOZ** [comment]
Ссылка на график нерабочая

**Comment by smgladkovskiy** [comment]
обновил

**Comment by biakaveron** [comment]
1. Поле `date_update` в таблице `modules` имеет смысл вынести в `module_info`, к прочей статистике. Таким образом, основная таблица не будет дергаться при каждом обновлении. 
2. Поле `fullname` в модели `Model_Module` объявлено как `unique`. При сохранении/обновлении модуля осуществляется проверка на его уникальность. Аналогично с `username` в `Model_Developer`.
   Имеет смысл пренебречь этой проверкой для краулера, так как она частично реализована на уровне кода (выборкой полученных от Github названий модулей и логинов разработчиков).
3. Выявлены проблемы с Jelly, вызывающие обновление записей при отсутствии формальных причин. В частности, [проблема](https://github.com/russiankohana/kohana-jelly/issues/2) с интерпретацией булевских значений.

**Comment by smgladkovskiy** [comment]
Как выяснилось, проблема была вызвана некорректной записью задания для cron'а: Скрипт вызывался каждую минуту целый час каждые 3 часа. :)

Сейчас всё гуд, поэтому закрываем проблему...

**Comment by biakaveron** [comment]
Что, впрочем, не отменяет вышеперечисленных проблем ;)
