### ISSUE TITLE
Сделать раздел Kohana powered sites

### ISSUE THREAD

**Issue by smgladkovskiy** [kohanaworld/kohana.world#21]
Сделать раздел "Kohana powered sites" в рамках портфолио участников и рейтингом, описанием, блекджеком и прочими прелестями... :)

**Comment by biakaveron** [comment]
Это ближе к jobs наверное, не?

**Comment by smgladkovskiy** [comment]
Jobs оно более обобщённое. Это как-то больше к портфолио разработчика. То есть, делать ещё тему для разработчика - портфолио. А из этого потом просто как галерея (с возможностью перехода к разрабу и предложение ему работы) работ на kohana...

**Comment by biakaveron** [comment]
Пообщались в аське, закрываю этот тикет дабы не палить тему ))
