### ISSUE TITLE
Модуль Auth

### ISSUE THREAD

**Issue by xbagir** [kohanaworld/kohana.world#22]
Для KW и будущих проектов, задумал написать модуль Auth. Так как текущий, коробочный Auth не устравивает по ряду вопросов:
1) Отсутсвие возможности прозрачно указать по каким полям вести авторизацию
2) Нет драйверов для авторизацию через OpenID и подобные системы (веренее есть, но в виде отдельных модулей).

Новый Auth планируется писать на основе bonafide. Хотелось бы услышать мнение по этому поводу

**Comment by dmitrievan81** [comment]
Хотелось бы мне например видеть не модуль auth, как узкое решение, а в более широком плане. Думаю нужен менеджер пользователей. auth - это конечно круто, но ведь круче еще, если бы была возможность иметь функционал, посмотреть кто онлайн ( например).

**Comment by dmitrievan81** [comment]
Ну и вообще можно подумать, что можно с пользователями делать для начала.

**Comment by xbagir** [comment]
ПРосмотр того, кто онлайн - помоему это это не задача Auth. Хотя bonafide уже тянет с собой ACL.

**Comment by biakaveron** [comment]
Мой подробный коммент был бессовестно съеден Гитхабом, поэтому пишу основные положения, как я себе представляю:
1. Все выносим в драйвера, даже вход по логину-паролю. Соответственно в любой момент времени можно подключить или убрать возможность входа, скажем, по OAuth.
2. На самом деле bonafide - это всего лишь инструмент для реализации одного драйвера (стандартный логин/пароль). Ну разве что ACL нам пригодится, но это отдельный модуль будет.
3. Есть таблица users(id, username), и есть таблицы драйверов oauth_users, password_users (названия от балды конечно) и т.д. Модуль Auth определяет, какой пользователь залогинен (в сессии лежит его id), и отправляет нужному драйверу (имя драйвера тоже надо как-то помнить) для загрузки модели данных пользователя.

@jeepda
 Auth не должен диктовать принципы работы с пользователями, это совершенно отдельная задача, и решаться она будет в другом модуле (админка или еще что-то)

**Comment by dmitrievan81** [comment]
А я и не писал, что он в аус нужен. Я писал, что нужно решение более широкое чем модуль - компонент типа. Чтобы там было все что касается работы с пользователями и администрированием.

**Comment by xbagir** [comment]
jeepda админка??? Я думаю может модуль потом отдельно написать, как раз чисто для работы с юзерами.

**Comment by AlexKupreev** [comment]
а почему не форк, а именно новый модуль? переписать с нуля будет проще, чем дорабатывать?

**Comment by biakaveron** [comment]
Структура должна полностью поменяться, одним форком не обойтись.

**Comment by zares** [comment]
Здорово не мудрите, ребята!
Сделайте для начала простое красивое решение на стандартном auth.
Или почему я изначально должен знать что есть такое bonafide? 
А хуже того - его клоны!..
Сегодня это есть, завтра - не актуально, в лучшем случае.
Не повторяйте ошибки тех, кто поверил в Jelly и др...

**Comment by biakaveron** [comment]
@zares 
На самом деле никто не мешает прикрутить пока что Auth так, чтобы потом безболезненно поменять его на что-то другое. Но писать свой Auth мы скорее всего будет, поэтому и необходимо как-то обсудить требования к нему.

**Comment by smgladkovskiy** [comment]
По обсуждениям в конфе, накатал [описание работы авторизации для kohana-world.com](http://goo.gl/zLcnO).

**Comment by smgladkovskiy** [comment]
упс, закрыл случайно... сорри.

**Comment by biakaveron** [comment]
Модуль расположен в репозитории https://github.com/kohana-world/kw-auth, в рамках проекта kohana-world будет прикручен в модуле https://github.com/kohana-world/kw-accounts.
