### ISSUE TITLE
Оформление списка модулей.

### ISSUE THREAD

**Issue by asuleymanov** [kohanaworld/kohana.world#25]
Предлагаю сделать список модулей в таком виде
https://docs.google.com/leaf?id=0B5_MMJWk6aoTYTZiNDhlZjMtMDVhNS00ZmVkLTk5NWMtYWM3YWFlZDQ1Mjgy&hl=ru&authkey=CI3m3o0J

**Comment by smgladkovskiy** [comment]
доступ...

**Comment by asuleymanov** [comment]
Доступ не требуеться. По идее

**Comment by asuleymanov** [comment]
Вот блин закрыл ненароком

**Comment by smgladkovskiy** [comment]
Цитирую:
"К сожалению, запрошенная вами страница (или документ) недоступна.
Проверьте правильность адреса и повторите попытку."

Либо не ту ссылку дал. нужно ту, которая генерится для доступа.

**Comment by asuleymanov** [comment]
https://docs.google.com/leaf?id=0B5_MMJWk6aoTYTZiNDhlZjMtMDVhNS00ZmVkLTk5NWMtYWM3YWFlZDQ1Mjgy&hl=ru&authkey=CI3m3o0J

Да может всетаки нету вот новая.
Я с этим google doc так ще до конца и не разобрался

**Comment by asuleymanov** [comment]
Вот новый вариант: https://docs.google.com/leaf?id=0B5_MMJWk6aoTYjA1YTk0MzgtMjRhYi00MTI0LTkxNDctYzlhNmNkNzM0ZDRm&hl=ru&authkey=COuL6qoH

**Comment by asuleymanov** [comment]
Вот еще вариант : https://docs.google.com/leaf?id=0B5_MMJWk6aoTNWJlMDM0NjgtMWRlMy00NDM1LTk3MzctMGU2OTQyYTU3NzAx&hl=ru&authkey=CKP4-YwJ

**Comment by AlexKupreev** [comment]
Тэгов может быть много, а места вы им отводите мало

может, стоит модули из одного репозитория как-нибудь визуально выделять?

если это вывод  списка в пределах категории, нужно ее как-то обозначить . аналогично с тэгом

рейтинги просятся визуально ближе к названию модуля, по крайней мере, общий рейтинг

**Comment by asuleymanov** [comment]
Так как тегов и категорий пока нет они по ширине совпали со словами которые туда вставлены. Т.е. поля расширяемое.
А как их визуально выделить. Их на странице по 10 штук. А если все разные что делать?
Так поле которое говорит о категории находиться рядом с полем тегов.
Есть мысль сделать как вы говорите, только с некоторыми дополнениями. Вот как предлагаю сделать:
https://docs.google.com/leaf?id=0B5_MMJWk6aoTY2I2NzdjMTUtMTQ2NS00MmQ4LWFmZTktNzA2MWEwNmVlZmU0&hl=ru&authkey=CKGphPwM

**Comment by AlexKupreev** [comment]
> Так как тегов и категорий пока нет они по ширине совпали со словами которые туда вставлены. Т.е. поля расширяемое.

а может, не в строку расширять, а сделать для тегов блочок сбоку гденить?

> А как их визуально выделить. Их на странице по 10 штук. А если все разные что делать?

Во-первых, почему 10? в идеале надо позволить посетителю выводить по  сколько ему надо - 10, 20, 50.. Если разные -- ничего не делать. А если есть из одного репозитория -- какнить визуально объединить (это я в порядке обсуждения предлагаю, может так и не надо)

> Так поле которое говорит о категории находиться рядом с полем тегов.

может, я неясно выразился, если выводим спсок модулей в категории, то в заголовке списка должна быть видна эта категория.

**Comment by asuleymanov** [comment]
> а может, не в строку расширять, а сделать для тегов блочок сбоку гденить?

Не совсем понял Вы имеете ввиду облако тегов чтоли?

> Во-первых, почему 10? в идеале надо позволить посетителю выводить по сколько ему надо - 10, 20, 50.

Думаю это будет. Но на данный момент пока 10.

> Если разные -- ничего не делать. А если есть из одного репозитория -- какнить визуально объединить (это я в порядке обсуждения предлагаю, может так и не надо)

Я если честно даже не представляю как это можно сделать.

> может, я неясно выразился, если выводим спсок модулей в категории, то в заголовке списка должна быть видна эта категория.

Ну это то скорее всего будет. Просто так как пока такого нету вывожу что есть. Думаю там стоит сделать так:
Если без категории то просто как сейчас.
Если с сортировкой по категории (любой) то просто после того что есть добавить двоеточие название категории. Но  это приделать быстро.

**Comment by asuleymanov** [comment]
Сделал практически все пожелания.
Остальное можно будет доделывать когда появиться необходимый функционал.

Если у кого какие пожелания или что то не так то пишите сюда обсудим.
Еще думаю стоит ли прикручивать JS к этой странице просто пару приколов сделалбы.

**Comment by asuleymanov** [comment]
Так как имееться общий тикет по дизайну сайта этот я закрою. Все предложени касаемые данного обсуждения предлагаю теперь вести в тикете номер 1.
