### ISSUE TITLE
Категории для модулей

### ISSUE THREAD

**Issue by asuleymanov** [kohanaworld/kohana.world#26]
Для их реализации предлагаю сделать таблицу с категориями. 
CREATE TABLE IF NOT EXISTS `module_category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(256) NOT NULL COMMENT 'category name',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

И добавить в таблицу  module_info поле category_id INT(10) и привязать его к полю id в таблице module_category.

**Comment by biakaveron** [comment]
1. Возможно, категории будут представлены в виде дерева. Соответственно надо определяться с механизмом его хранения (Nested Sets наверное оптимально, нет?).
2. Еще наверное стоит добавить поле `url` или что-то вроде (как будет представлено имя категории в виде сегмента УРЛа).

**Comment by asuleymanov** [comment]
1) А имеет ли смысл делать дерево? Это тогда становиться сильно похоже на тэги.
2) Да вот про это не подумал.

**Comment by NARKOZ** [comment]
Не думаю, что древовидные категории хорошая идея

**Comment by biakaveron** [comment]
Предлагаю не разбивать обсуждение по разным тикетам, используем этот - https://github.com/kohana-world/kohana-world.com/issues/8 в качестве основного
