### ISSUE TITLE
Момент упущен ?

### ISSUE THREAD

**Issue by slider23** [kohanaworld/kohana.world#29]
Месяц назад разрабами поднимался вопрос об интеграции kohana-modules.com в основной сайт коханы.

Isaiah said he’d contact Andrew Hutchings about using kohana-modules.com for kf.org. Some kind of json file to list dependencies on say kohana, other modules etc.
http://dev.kohanaframework.org/issues/4164

**Comment by smgladkovskiy** [comment]
В тикете речь идёт об интеграции к kohana-modules.com. Но до конкретной реализации ещё не дошло, как я понял. Типа, кто-то с кем-то должен поговорить, обсудить, но, уверен, ещё никто не договорился и не поговорил...

Так что время ещё не ушло, а мы спокойно сможет сделать внешнее api для основного сайта..;)

**Comment by smgladkovskiy** [comment]
Работаем, пока ещё солнце в небе..:)

**Comment by slider23** [comment]
<s>Кац предлагает сдаться</s>
Я подниму тему, поднятую мною весной - а может форкнуть имеющийся kohana-modules.com и допилить ?

**Comment by biakaveron** [comment]
Плохо, что мы пока не можем ничего запустить такого, что смогли бы показать для начала другим коханерам... Дизайн нас конечно тормозит.

**Comment by biakaveron** [comment]
@medar
А принципиально что нам от kohana-modules нужно? Что там такого интересного, что мы не смогли бы сделать? Кроме ****го дизайна конечно :)

**Comment by slider23** [comment]
Время. У нас, конечно, свой луна-парк, но за это время мы вместе с Andrew Hutchings давно бы сделали нормальный плагин-репозиторий.

Я, к сожалению, только весной начал осваивать этот фреймворк, не мог поучаствовать в разработке плотно.

**Comment by smgladkovskiy** [comment]
@biakaveron, @medar
Что там такого интересного, что мы уже не сделали, но никак не запустим, так как нет дизайна? :)

**Comment by xbagir** [comment]
А скрин же дизайна был. Или работу не приняли?

**Comment by smgladkovskiy** [comment]
@xbagir
решили переделать, да вот застряли...

**Comment by biakaveron** [comment]
Тикет по дизайну [тут](https://github.com/kohana-world/kohana-world.com/issues/1), а последние замечания и картинки - [там](https://docs.google.com/document/d/1G2zveZe3whZHi39ghjsVyGFHjIN0q0Z7kfxEu-JQgiM/edit?hl=ru)

**Comment by biakaveron** [comment]
если есть замечания/предложения, можно поболтать в опустевшем jabber-чате ))

**Comment by smgladkovskiy** [comment]
все в наш уютный трактирчег?:)

**Comment by biakaveron** [comment]
закрываю, т.к. выяснилось, что мы еще живы ;)
