### ISSUE TITLE
организация хостинга

### ISSUE THREAD

**Issue by smgladkovskiy** [kohanaworld/kohana.world#5]
Думаю, что стоит зарегистрировать домен под эту затею.

Будет домен, можно будет организовать хостинг.
Как вариант, до переезда на официальную площадку сообщества, могу предложить в аренду место для размещение сайта и базу данных.
Чтобы не было неудобств, можно сделать поддомен для разработческой ветки, чтобы можно было по крону делать пулл мастер и дев ветки и смотреть работу в сети. Тем самым, доступ до сервера не потребуется.
Базу можно сделать как для общего доступа в режиме чтения (в ознакомительных целях), так и персонально (с правами чтения/записи) разработчикам.

Вопросы/предложения приветствуются.

**Comment by ukko** [comment]
хостинг - это конечно правильно, и он обязательно потребуется к окончанию майлстоуна.

У меня только одна просьба, Иван, конкретно к тебе и по поводу хостинга - ко всем остальным.

Предоставляете хостинг - создайте ещё хотя бы одного пользователя помимо себя, на случай если вы не сможете обновлять, уедете, попадёте в больницу и т.д. что бы всё не замыкалось на одном человеке.

Иван, дай кому-нибудь ещё овнера, что бы опять же не замыкать всё на себя одного и что бы проект мог развиваться в самый непридвиденных ситуациях.

**Comment by smgladkovskiy** [comment]
Поддерживаю!

По поводу хостинга с управлением проще: достаточно, чтобы несколько людей управляло настройками домена.
До файловой системы доступ не обязателен, так как повешу обновление репозитория с гихаба на интервал в 1-5 минут (сейчас у меня вертится крон на обновление всех гит проектов кажедые 5 минут).
До БД у разработчиков будет доступ, поэтому, если со мной что-то случится (тьфу-тьфу-тьфу), то перенести проект будет очень легко.

Если же что-то случится с сервером, то уж поверьте - меня из-под земли достанут, чтобы он заработал... :)

**Comment by biakaveron** [comment]
Добавил вас обоих в команду владельцев.

**Comment by smgladkovskiy** [comment]
Ок. И пусть со всеми будет всё хорошо, никто не болел и отдыхал с доступом в инет! :)

**Comment by smgladkovskiy** [comment]
Так, домен есть. Пора, кажется, задуматься о хостинге.

Я вижу это так:
чтобы не покупать его, собираем предложения о возможных вариантах предоставления серверных мощностей. То, что на сервере должно быть, чтобы не заморачиваться с предоставлением shell-доступа и всё работало:
- **PHP 5.3** хорошо бы php-fpm, но можно и модулем к Apache
- **web-сервер** в идеале - nginx/lighttpd
- **git** куда ж без него :)
- **расширения и всякие плюшки к интерпретатору** всё должно работать быстро и качественно
- **MySQL-сервер** Для удобства можно иметь phpmyadmin. Должны быть доступы до базы 2х видов: 1 общий для чтения, чтобы народ мог поглядеть структуру (через pma, либо напрямую); частный для разработчиков с привилегиями до базы на CRUD.

Если что упустил или пишу не то, комментируем. Собираем несколько заявок, обсуждаем и выбираем. До конца недели (06.02) стоит определиться и начать что-то делать...

**Comment by smgladkovskiy** [comment]
могу со своей стороны предложить следующую площадку:

Linux (Gentoo) Server (ядро 2.6.30), на Xeon E5520, 16G оперативки с достаточным для проекта дисковым пространством (однако, на SATA), 100 Мб/с канал.
PHP-5.3.3 (php-fpm, apc, memcached, suhosin + всё, что нужно для Коханы), nginx, MySQL Innodb оптимизированный.

**Comment by klinkov** [comment]
Мда, у нас попроще раза в 2 площадка.

**Comment by biakaveron** [comment]
Полагаю, на данный момент можно тикет прикрыть?

**Comment by smgladkovskiy** [comment]
думаю, что стоит повисеть ему ещё немного, чтобы проявились товарищи, которые могли бы, в случае чего, предоставить площадку... Приоритет смени только.

**Comment by smgladkovskiy** [comment]
Желающих не нашлось, думаю, стоит закрывать...
