### ISSUE TITLE
Инструментарий

### ISSUE THREAD

**Issue by biakaveron** [kohanaworld/kohana.world#6]
Предлагаю оговорить используемые средства проектирования. Тем более, что предполагается создание и редактирование проектных файлов (та же структура БД).
- Для БД уже предлагали [MySQL Workbench](http://dev.mysql.com/downloads/workbench) - полностью согласен, удобная штука.
- Для проектирования различного рода диаграмм проекта мне понравился [Xmind](http://www.xmind.net/). Может кто еще что-то предложит.
- UML диаграммы - [DIA](http://live.gnome.org/Dia/Download).

**Comment by ukko** [comment]
Оба средства хороши. Но xmind - это просто майндмеппинг. Если нужен UML я бы использовал DIA

**Comment by biakaveron** [comment]
Никогда особо не любил UML 0_o
Ок, DIA добавляю

**Comment by biakaveron** [comment]
закрываю за неактуальностью
