### ISSUE TITLE
Категории

### ISSUE THREAD

**Issue by NARKOZ** [kohanaworld/kohana.world#8]
- Разбить модули по категориям
- Сделать сортировку в категориях по популярности

Пример того как хотелось бы - [ruby-toolbox.com](http://ruby-toolbox.com)

**Comment by biakaveron** [comment]
Я ничего на данном сайте не понял :) Как-то неудобно сделано, ИМХО. Хотя сами по себе категории (как и тэги) нужны. Причем, я полагаю, надо сделать связь ManyToMany (проект можно впихнуть в несколько категорий)

**Comment by ukko** [comment]
Может одними тегами можно обойтись?

Но не создавать очень много тегов, а так.. штук 30 не больше.

**Comment by NARKOZ** [comment]
Модулей много, одними тегами не обойтись

**Comment by biakaveron** [comment]
Я себе представляю, что категории будут в ручном режиме управления (модераторами, плюс автор модуля может "попроситься" в какой-то), а тэги может любой зарегенный пользователь с какой-то положительной репой прикрепить. Например, в категорию recommended можно положить модули из репозитория kohana плюс еще несколько самых популярных и развивающихся.

Кстати, еще один пунктик для разработки - репутация пользователей :)

**Comment by ukko** [comment]
Да, точно.. И категории и теги нужны. Репутация пользователей - тоже :)

**Comment by paulchubatyy** [comment]
не ну репутация пользователей это вы загнули. Это не социальный ресурс, а каталог модулей. Не забываем.

**Comment by ukko** [comment]
Пользователи - они же авторы. Всегда высокая репутация поддерживает энтузиазм.

К тому же мы не хотим просто каталог модулей. Нам сразу нужна была социальность.

**Comment by biakaveron** [comment]
Мы зарегали такой вкусный домен не для того, чтобы только модули туда складывать :lol: Потом еще прикрутим QA, форум с блэкджеком и прочее. Так что будем планировать фичи с учетом будущего развития

**Comment by AlexKupreev** [comment]
а можно четко сформулировать, каким вы видите принцип разбиения по категориям, а каким -- по тэгам?

**Comment by biakaveron** [comment]
Гм.. Например, категория "рекомендуемые". :) В общем, это некоторое ограниченное количество групп, скорее всего с ручной модерацией. А тэгов можно создавать сколько угодно.

**Comment by AlexKupreev** [comment]
Если тэгов можно создавать сколько угодно кому угодно (из зарегистрированных пользователей), то как воспрепятствовать появлению тэгов-синонимов типа "kohana3.2", "kohana 3.2" и "ko3.2" ? Возможное решение -- система "жалоб", то есть на неправильный по чьему-либо мнению тэг можно пожаловаться модератору, который совершит скорый и справедливый суд. Правда, для этого нужно предусмотреть возможность переназначения тэгов, а также страховку от полного удаления тэгов -- тогда модуль невозможно будет отыскать.

Кстати, неплохо было бы устроить "ступенчатую фильтрацию" -- разрешить применять тэги к уже отфильтрованному содержимому. Например, сначала фильтруем по "kohana 3.0", затем выдачу по "authentication", например.

**Comment by NARKOZ** [comment]
Категории модулей: формы, email, изображения и т.д. А теги можно: beta, stable и т.д. Еще можно RSS ленту сделать для категорий.

**Comment by ukko** [comment]
Так, давайте внёсём ясность..

Категории: база данных, шаблонизаторы, популярные, рекомендуемые, и т.д.
Теги: jelly, orm, migration, image, 
Версии: Kohana 3.0.9, Kohana 3.0.*, Kohana 3.1 (предлагаю в модулях ввести зависимости от версий. От такой-то, до такой-то. Как в файрфоксе)

Версии должны быть отдельной сущностью, это прежде всего версии для коханы, но скорее всего можно будет указывать версии конкретного модуля

**Comment by biakaveron** [comment]
1. Желательно, чтобы тэги могли устанавливать только уполномоченные юзеры (модераторы и пользователи с кучей медалек, т.е. высокой репой). Все остальные могут предложить тэг, т.е. отправить модераторам сообщение.
2. Да, тэги надо уметь складывать, т.е. типа tag/jelly+form.
3. Вообще надо бы накидать справочники синонимов, чтобы тэги "Ko3", "Kohana 3", "Kohana v3" и т.д. автоматически преобразовывались к какому-то одному варианту. Интересно, нужно ли нам слово "Kohana" вообще, если сайт посвящен одному фреймворку?
4. С версиями сложнее. От конкретной версии fw зависит не сам модуль, а его конкретный тэг (релиз). Зависимость от версий других модулей (например, ORM-MPTT от ORM), полагаю, можно не учитывать. Хотя в теории из github'а можно попробовать выдернуть последний использованный коммит и узнать версию модуля, к которому он принадлежит. Но как-то геморно.

**Comment by wertex** [comment]
А если при добавлении теги предлагать в виде списка, имхо их все равно ограниченное количество.

Их можно просто все отобразить:
| база данных | шаблонизаторы | популярные | etc |
а при нажатии на тег он будет подсвечен
| >база данных< | шаблонизаторы | популярные | etc |

**Comment by biakaveron** [comment]
Как раз-таки тэгов-то теоретически может быть сколько угодно

**Comment by smgladkovskiy** [comment]
К списку модераторов тегов, думаю, стоит причислять и автора модуля, для внесения данных по его разработке.

Иван, по поводу складывающихся тегов поясни, плз. Если я правильно понял, то данных функционал удобней бы реализовать в поиске по тегам (мультипл автокомплит, к примеру)...

Справочник синонимов сформировать нужно. Но это уже задача оптимизации, имхо. пока нет справочника тегов, синонимы для них придумывать бессмысленно. :) Но как Feature Request оставить нужно...

Версии нужно заставлять указывать авторам. В любом случае, моё мнение таково, что помимо работы бота, должна быть работа пользователя. Модули должны проходить премодерацию, чтобы инфа не терялась и можно было бы понять, заинтересован ли автор в своей разработке. Если пошёл на контакт и внёс инфу, модуль помечается как проверенный и начинает появляться во всех выдачах. До этого - пусть будет лежать в песочнице...

**Comment by biakaveron** [comment]
Зачем автора включать? Мы и так его авторство укажем. К тому же часто помимо собственно владельца есть несколько разработчиков, причем мы их через Github API вытянем спокойно и тоже отобразим. Или ты для включения в поиск по тэгам? Типа найти все ORM от Shadowhand?

Да, при поиске по тэгам. 

Со справочником согласен, это позже. Просто упомянул о такой необходимости.

**Comment by smgladkovskiy** [comment]
Я про управление метаданными модуля. Чтобы автор мог проставить теги, модератор мог проставить теги, администратор мог...

**Comment by AlexKupreev** [comment]
написал целую кучу всего, думал контролЦэ перед постингом -- но понадеялся на гитхаб. А он все похерил, потому что отправлял со страницы репо kohanamodules :). Поэтому повторюсь кратко
1. **Категории**
   Пример: "база данных", "управление пользователями"
   Особенности:
   - соответствуют общим решаемым задачам
   - каждый модуль может быть только в одной категории
2. **Тэги**
   Пример: "jelly", "oauth", "xml"
   Особенности: 
   - описывают особенности функционала или реализации модуля
   - модуль может быть помечен любым количеством тэгов
3. **Версии фреймворка**
   Пример: 3, 3.0.9, 3.0-3.1.1
   Особенности:
   - при поиске должны поддерживаться диапазоны версий, например, если модуль помечен как 3, то должен находиться и по 3.1, и по 3.0.6.
   - очень желательно предусмотреть тестирование на совместимость, то есть помечать модуль версией только после чьего-либо тестирования. Что-то типа "tested with kohana 3.0.6 - 3.1. Not tested with kohana 3.2. Please inform us after testing" и ссылку на форму обратной связи
   - не думаю, что стоит категоризировать по версиям самого модуля
4. **Особые отметки**
   Пример: recommended, well documented
   Особенности:
   - может быть отмечен только при соответствии определенным критериям, что проверяет модератор (не уверен, нужно ли как-то особо выделять автоматически рассчитываемые штуки типа самого высокого рейтинга). 
   - иконка для привлечения внимания

Что я написал не так или забыл написать?

**Comment by biakaveron** [comment]
1. Надо подумать, может ли быть вероятность отнесения модуля к нескольким категориям.
2. Да, судя по всему, версии надо будет хранить в виде дерева. Тут не столько тестирование, сколько просто сбор отзывов о совместимости с разными версиями. 
   Опять же, совместимость может отличаться от версии к версии. Мне нравится как в плагинах ФФ [сделано](https://addons.mozilla.org/ru/firefox/addon/firephp/versions/)

**Comment by paulchubatyy** [comment]
1. Сейчас конечно запинаете, но можно сделать как с плагинами вордпресса, чтобы пользователи сами отмечали работает ли модуль с версией kohana. Как дополение к идее Ивана (плагины к FF)

**Comment by biakaveron** [comment]
Ну, я собственно так и предлагаю - у нас же социальный сайт :)

**Comment by NARKOZ** [comment]
Тогда можно и что-то в духе "победитель месяца" и ярлык прикрепить к этому модулю.

**Comment by AlexKupreev** [comment]
> Надо подумать, может ли быть вероятность отнесения модуля к нескольким категориям.

я не настаиваю на исключительном отнесении модуля к одной категории, поскольку еще не решил как будет удобнее. Однако полагаю, что для Коханы более характерен unix-way, то есть модули выполняют специфичные задачи.  

> чтобы пользователи сами отмечали работает ли модуль с версией kohana 

Можно. Хотя не очень надежно, но ведь и не каждый модуль покрыт тестами. Но можно все же оставить кнопочку типа "пожаловаться на несовместимость", если у кого-то заявленный рабочим модуль не заработает

> совместимость может отличаться от версии к версии. Мне нравится как в плагинах ФФ сделано

На первое время можно рассматривать только совместимость текущей стабильной версии. Но идея разделять совместимость разных версий модуля разумная. Вопрос в том, как определять эти версии. По тэгам гита?

**Comment by biakaveron** [comment]
Раз уж мы используем модуль Github'а, то только по тэгам :)

**Comment by biakaveron** [comment]
Пока закрываю. При наличии первой версии будем обсуждать дальнейшее развитие.
