### ISSUE TITLE
Используемые в проекте модули

### ISSUE THREAD

**Issue by biakaveron** [kohanaworld/kohana.world#9]
Предлагаю пока тут пообсуждать различные модули, которые будем подключать к проекту. Итак, нам понадобятся модули для следующих задач:
- ORM. Поскольку планируется использовать данный проект и в качестве обучающего, предлагаю тупо юзать родной ORM. Торжественно обязуюсь написать про него статью в ближайшее время :) На тот же unstable Jelly перейти никогда не поздно, но пока что я не вижу особых "выкрутасов" для его прикручивания. Хотя конечно было интересно попутно вносить отсебятину в этот умирающий проект. Sprig развивается, но, честно говоря, после Jelly ничего другого уже не хочется...
- Github. Модуль для работы с github через его API. Пока вижу только [этот](https://github.com/ahutchings/kohana-github). Может кто еще какой знает?
- OAuth. Для авторизации на сторонних ресурсах (тот же github). Вроде как имеется [неплохой модуль](https://github.com/kohana/oauth) от Shadowhand'а.
- Gravatar. Понятно для чего. Имеется [разработка](https://github.com/samsoir/kohana-gravatar) от Samsoir.
- Email. Вроде как [этот](https://github.com/banks/kohana-email) неплохой, от banks'а.

Плюс родные модули:
- Cache
- Database
- Pagination
- Unittest

**Comment by paulchubatyy** [comment]
Полностью поддерживаю выбор модулей. Приведенный модуль Github вполне подходит для наших целей, так как он клеит github API к kohana, а нам не нужно ни больше ни меньше.

По поводу OAuth: разве github является OAuth провайдером? Логично было бы давать возможность авторизоватся пользователям именно с github профиля, а не с facebook или там google.

**Comment by ukko** [comment]
Ещё нужен модуль авторизации Auth.

**Comment by paulchubatyy** [comment]
Да, и наверное неплохо будет добавить модуль cache.

**Comment by biakaveron** [comment]
Да, у Github'а [есть OAuth](http://habrahabr.ru/blogs/symfony/112653/#comment_3607359) :) Сам вчера офигел. Хотя для прочих юзеров лучше оставить Гугл с ЛицеКнигой.

Насчет Auth не знаю даже :) Нужно ли оно нам? Предположим, что у нас есть вход по OpenID и OAuth. Мне кажется, вполне достаточно... Вот насчет ACL надо подумать. В теории может пригодиться, когда кроме админов появятся модераторы...

Ну а Cache я задним числом и так считал, как стандартный модуль вместе с Database и прочими.

**Comment by biakaveron** [comment]
Еще один пункт. Будем брать оригинальные модули или форкать их? Во втором случае имеется возможность добавлять свои коммиты и не ждать реакции создателей (например, если модуль не развивается).

**Comment by biakaveron** [comment]
И еще. Удобно пользоваться модулем для хранения разного рода сообщений между реквестами. В kohana-modules.com есть [notices](https://github.com/synapsestudios/kohana-notices), я писал аналогичный [message](https://github.com/biakaveron/message) для себя. Соответственно первый я не пользовал, не знаю как он и что он :)

UPD. Есть еще парочка - [MSG](https://github.com/goyote/msg) от goyote и [message](https://github.com/GeertDD/kohana-message) от GeertDD

**Comment by smgladkovskiy** [comment]
Мне кажется, модули лучше оригинальные. В любом случае, практически вс подразумевают возможность расширения. Если наше изменение или корректировка работы модуля будут значительны (а не под задачу), то можно сделать форк и внести изменения пул реквестом. Но, как мне кажется, уже как отдельной задачей. Будет прикольно, если это будет не в рамках создания ресурса, а, так сказать, от организации..:)

**Comment by biakaveron** [comment]
Интересный [модуль](https://github.com/aberdnikov/kohana-static-files), опубликованный на [Хабре](http://habrahabr.ru/blogs/kohanaphp/112852/), напомнил о необходимости работы с ресурсами (js/css/img). Выглядит неплохо.

**Comment by smgladkovskiy** [comment]
Ага, на недельке оттестирую и доложу о результатах... По мне так для оптимизации самое оно!

**Comment by smgladkovskiy** [comment]
Попробовал я этого зверя... Как-то всё писано как курица лапой. Поправил пару корявостей, оптимизировал чутка код и отформатил под kohana coding style. Тестил только на манер локальных файлов, но, думаю, мы в ближайшее время на CDN переходить не собираемся..:)

В целом, результатом доволен: холостых коннектов стало меньше, iowait на сервере тоже снизился, выдаётся и работает всё пучком.

Предварительный вердикт - полезная либа. Вот наведу лоска и сделаю пулл реквест автору. Там поглядим, примет он изменения или нет, а то на хабре товарищ как-то не решился прогибаться под установленные правила, а рекомендуемые изменения не принял к сведению...

**Comment by biakaveron** [comment]
На крайняк отпочкуемся и свой форк будем вылизывать ))

А написано, согласен, весьма специфично.

**Comment by smgladkovskiy** [comment]
Возможно, это стоит запостить в "инструментарий", но попробую тут.

Никто не хочет попробовать использовать LESS?
http://lesscss.org/

:)

**Comment by smgladkovskiy** [comment]
Вернее, не так.

**А давайте использовать LESS!!!**

**Comment by biakaveron** [comment]
Интересно, это как-то связано с событием "smgladkovskiy started watching cloudhead/less.js about 5 hours ago"? ))

**Comment by smgladkovskiy** [comment]
)))) Блин, пропалили! 

Просто тема интересная, хочется попробовать, а все доступные проекты в работе уже прошли стадию вёрстки. :)

**Comment by smgladkovskiy** [comment]
Ну, если уж на чистоту, то вот: http://twitter.github.com/bootstrap/

**Comment by biakaveron** [comment]
Зачем нам этот тикет? Для новых модулей лучше делать отдельные тикеты с обсуждением их необходимости. Предлагаю закрывать.

**Comment by smgladkovskiy** [comment]
Нужен тогда перечень используемых модулей с описанием, где они используются...

**Comment by biakaveron** [comment]
Делаем страничку в wiki, там все расписываем. Можно даже целый раздел, со сводной таблицей и отдельными страницами для каждого модуля.

**Comment by smgladkovskiy** [comment]
true

**Comment by biakaveron** [comment]
Заготовка [тут](https://github.com/kohana-world/kohana-world.com/wiki/Modules-in-use). Закрываю
